"""auto update

Revision ID: 1e3dcbef609f
Revises: 294a2b2b2225
Create Date: 2026-03-08 14:09:01.633091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3dcbef609f'
down_revision: Union[str, Sequence[str], None] = '294a2b2b2225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_progresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('service_stage', sa.String(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('sales_person', sa.String(), nullable=True),
    sa.Column('ops_person', sa.String(), nullable=True),
    sa.Column('design_person', sa.String(), nullable=True),
    sa.Column('package_name', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('service_start_date', sa.String(), nullable=True),
    sa.Column('service_end_date', sa.String(), nullable=True),
    sa.Column('last_update_time', sa.String(), nullable=True),
    sa.Column('last_update_person', sa.String(), nullable=True),
    sa.Column('last_work_summary', sa.String(), nullable=True),
    sa.Column('issue_status', sa.String(), nullable=True),
    sa.Column('issue_description', sa.String(), nullable=True),
    sa.Column('issue_found_date', sa.String(), nullable=True),
    sa.Column('issue_owner', sa.String(), nullable=True),
    sa.Column('issue_resolved', sa.Boolean(), nullable=True),
    sa.Column('issue_resolved_date', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_progresses_id'), 'service_progresses', ['id'], unique=False)
    op.create_table('service_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_progress_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('assignee_name', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('completed_date', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_tasks_id'), 'service_tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_tasks_id'), table_name='service_tasks')
    op.drop_table('service_tasks')
    op.drop_index(op.f('ix_service_progresses_id'), table_name='service_progresses')
    op.drop_table('service_progresses')
    # ### end Alembic commands ###