"""auto update

Revision ID: 294a2b2b2225
Revises: a10bf947e8b5
Create Date: 2026-03-08 12:21:47.867665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '294a2b2b2225'
down_revision: Union[str, Sequence[str], None] = 'a10bf947e8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('login_email', sa.String(), nullable=True),
    sa.Column('login_password', sa.String(), nullable=True),
    sa.Column('bound_phone', sa.String(), nullable=True),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('account_status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_accounts_id'), 'media_accounts', ['id'], unique=False)
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('action_detail', sa.String(), nullable=True),
    sa.Column('operator_name', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_logs_id'), 'operation_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_logs_id'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index(op.f('ix_media_accounts_id'), table_name='media_accounts')
    op.drop_table('media_accounts')
    # ### end Alembic commands ###