"""add_composite_unique_constraint_to_system_options

Revision ID: 8c22d4d366d0
Revises: cf1970d2e333
Create Date: 2026-03-16 04:08:53.571507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c22d4d366d0'
down_revision: Union[str, Sequence[str], None] = 'cf1970d2e333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_options', schema=None) as batch_op:
        batch_op.drop_index(op.f('ix_system_options_key'))
        batch_op.create_index(op.f('ix_system_options_key'), ['key'], unique=False)
        batch_op.create_unique_constraint('_category_key_uc', ['category', 'key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_options', schema=None) as batch_op:
        batch_op.drop_constraint('_category_key_uc', type_='unique')
        batch_op.drop_index(op.f('ix_system_options_key'))
        batch_op.create_index(op.f('ix_system_options_key'), ['key'], unique=True)
    # ### end Alembic commands ###
