"""add_system_options_table

Revision ID: cf1970d2e333
Revises: 3a4981e5cf2d
Create Date: 2026-03-16 04:05:53.826737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1970d2e333'
down_revision: Union[str, Sequence[str], None] = '3a4981e5cf2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_options_category'), 'system_options', ['category'], unique=False)
    op.create_index(op.f('ix_system_options_id'), 'system_options', ['id'], unique=False)
    op.create_index(op.f('ix_system_options_key'), 'system_options', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_options_key'), table_name='system_options')
    op.drop_index(op.f('ix_system_options_id'), table_name='system_options')
    op.drop_index(op.f('ix_system_options_category'), table_name='system_options')
    op.drop_table('system_options')
    # ### end Alembic commands ###
